jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package  # Generates target/app.jar

      - name: Rename JAR for Docker
        run: mv target/*.jar app.jar  # Move app.jar to root

      - name: Upload JAR as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-jar
          path: app.jar  # Corrected path

  docker:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download JAR from Build Job
        uses: actions/download-artifact@v3
        with:
          name: built-jar
          path: .

      - name: Build, tag, and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_NAME: java-app
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME .
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
