name: Java CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package  # This generates target/*.jar

      - name: Upload JAR as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: target/*.jar

  test:
    runs-on: ubuntu-latest
    needs: build  # Ensure tests run only after build succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests with Maven
        run: mvn test

  docker:
    needs: [build, test]  # Ensures build & test succeed before deploying
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download JAR from Build Job
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: target  # Ensures the JAR is available for Docker

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_NAME: java-app
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME .
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
